import type { Metadata } from "next";
import "./globals.css";
// import PrelineScript from "@/components/Preline";
import { Providers } from "./Provider";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <Providers>
            <NavBar/>
            {children}
          </Providers>
        </body>
    </html>
  );
}
